apiVersion: v1
entries:
  jaeger-all-in-one:
  - apiVersion: v2
    appVersion: "1.55"
    created: "2024-10-01T14:53:17.086053-03:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: d1e24523414c22ee2356a0cb6858ceaae78240d92ff33f2b1e8ef745a469e702
    home: https://github.com/schoren/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/schoren/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.12.tgz
    version: 0.1.12
  - apiVersion: v2
    appVersion: "1.47"
    created: "2024-10-01T14:53:17.080875-03:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: 8943810055acc00f6bfc8bb1589f28f591f51ce444dc63bec13e7ec360ce25b1
    home: https://github.com/hansehe/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/hansehe/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.11.tgz
    version: 0.1.11
  - apiVersion: v2
    appVersion: "1.46"
    created: "2024-10-01T14:53:17.080429-03:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: a0a23e40853c45afcf10b704a5a5feb8b073e58c530da8bf416bc8ce32f9257f
    home: https://github.com/hansehe/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/hansehe/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.10.tgz
    version: 0.1.10
  - apiVersion: v2
    appVersion: "1.46"
    created: "2024-10-01T14:53:17.090115-03:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: 1f989787ce86924cb0fa99976226de8e910c0e2e7adac7de70602452f5ab3b80
    home: https://github.com/hansehe/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/hansehe/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: 1.41.0
    created: "2024-10-01T14:53:17.089697-03:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: b5586e6e002be745c524e67c0e6de9a0172bde86da34f84d6cd84c21e597986e
    home: https://github.com/hansehe/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/hansehe/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    appVersion: 1.22.0
    created: "2024-10-01T14:53:17.089308-03:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: c69376758939b6fb547092f650aaf14e1b4affe192643846a5c1165141f2bf4c
    home: https://github.com/hansehe/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/hansehe/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 1.22.0
    created: "2024-10-01T14:53:17.088901-03:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: fcbff209f1a8e0fe448026bb780a77f2beb1121689071023d966044f6dbf17ba
    home: https://github.com/hansehe/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/hansehe/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 1.22.0
    created: "2024-10-01T14:53:17.087748-03:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: e336b32e3da961d3850974ea0275a42cb9544eef75cd85910b3eb9fa52412a38
    home: https://github.com/hansehe/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/hansehe/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 1.22.0
    created: "2024-10-01T14:53:17.08732-03:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: 80e6e273228bc6eada30e0b0db7c60b34fcce9ebfadc20d76daf3d54f4112ea7
    home: https://github.com/hansehe/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/hansehe/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 1.22.0
    created: "2024-10-01T14:53:17.086916-03:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: d768d031e3ffbf0353894a86a7863209cb1dbd386a01e83315ef58b5fe7a1583
    home: https://github.com/hansehe/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/hansehe/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 1.21.0
    created: "2024-10-01T14:53:17.086496-03:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: 80c3ea39410998f562ce6ae1fb9e71a8ade7dc8b9b9b0f9a5cfbbd2d72c727bb
    home: https://github.com/hansehe/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/hansehe/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 1.21.0
    created: "2024-10-01T14:53:17.079846-03:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: 68985c4defdb1808c3fdf2093c7dc4c062868f79fbf8cde8c3da917fecdf44d1
    home: https://github.com/hansehe/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/hansehe/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.21.0
    created: "2024-10-01T14:53:17.079318-03:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: ab7b3e8d18cf833825845d39681d89047496e5f88a37ad699e17a46efbb48e4b
    home: https://github.com/hansehe/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/hansehe/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.0.tgz
    version: 0.1.0
generated: "2024-10-01T14:53:17.078454-03:00"
